/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    A_card: THREE.Mesh;
    A: THREE.Mesh;
    A_card001: THREE.Mesh;
    A001: THREE.Mesh;
    A_card002: THREE.Mesh;
    A002: THREE.Mesh;
    A_card003: THREE.Mesh;
    A003: THREE.Mesh;
    Text: THREE.Mesh;
  };
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

export function LogoUnani(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    './model/trial logo - no animation.glb'
  ) as unknown as GLTFResult;
  return (
    <group
      {...props}
      dispose={null}
      position={[-3, 0, 0]}
      rotation={[Math.PI / 2, 0, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A_card.geometry}
        material={materials['Material.002']}
        position={[0.34, 0, -0.42]}
        rotation={[0, 0.16, 0.01]}
        scale={[0.5, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A.geometry}
        material={materials['Material.001']}
        position={[0.08, 0, -0.01]}
        rotation={[0, 0.16, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A_card001.geometry}
        material={materials['Material.002']}
        position={[1.22, 0.01, -0.55]}
        rotation={[0, 0.05, 0]}
        scale={[0.5, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A001.geometry}
        material={materials['Material.001']}
        position={[0.91, 0.01, -0.18]}
        rotation={[0, 0.05, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A_card002.geometry}
        material={materials['Material.002']}
        position={[2.19, 0.01, -0.59]}
        rotation={[0, 0.01, 0]}
        scale={[0.5, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A002.geometry}
        material={materials['Material.001']}
        position={[1.87, 0.01, -0.24]}
        rotation={[0, 0.01, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A_card003.geometry}
        material={materials['Material.002']}
        position={[3.06, 0.01, -0.59]}
        rotation={[0, -0.03, 0]}
        scale={[0.5, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.A003.geometry}
        material={materials['Material.001']}
        position={[2.72, 0.01, -0.24]}
        rotation={[0, -0.03, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['Material.002']}
        position={[3.76, 0, -0.26]}
      />
    </group>
  );
}

useGLTF.preload('./model/trial logo - no animation.glb');
