name: Build cache

on:
  [ push ]

env:
  node_version: "16.x"

jobs:
  build-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}
        cache: yarn
    - uses: c-hive/gha-yarn-cache@v3
    - name: Install JS dependencies
      run: yarn install --prefer-offline