name: Set up Node.js
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  uses: actions/setup-node@v3
  with:
    node-version: '16'
    cache: 'yarn'

name: Install project dependencies
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  run: yarn --prefer-offline

name: check-formatting
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn format
      - run: yarn lint
  test-deck-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: yarn vitest run deck
